### ISSUE TITLE
Смена статуса заказа

### ISSUE THREAD

**Issue by Galeups** [yandex-money/yandex-money-cms-modx#1]
Здравствуйте!
Заметил, что при оплате картой на странице яндекс.касса, после заполнения данных, и нажатии Оплатить, если в данных допущена ошибка и оплата не проходит, то заказ в админ панели Shopkeeper все равно меняет статус, как "Как оплата получена".

**Comment by ikarmanov** [comment]
Спасибо. Нужно время на проверку.

**Comment by ikarmanov** [comment]
Мы [обновили](https://github.com/yandex-money/yandex-money-cms-modx/releases/tag/1.3.0) модуль и проблема со статусами решена.
