### ISSUE TITLE
Стартовые настройки сниппета YandexMoney

### ISSUE THREAD

**Issue by alexbom** [yandex-money/yandex-money-cms-modx#6]
Расскажите, пожалуйста, какие именно настройки сниппета YandexMoney необходимо установить для начала работы, кроме shopid и password?

**Comment by ostulov** [comment]
Для приема оплаты через Яндекс.Кассу необходимо указать:
shopid
scid
shopPassword
выбрать режим приема платежей и выбора способа оплаты
при необходимости включить отправку данных для фискализации
