### ISSUE TITLE
IP-адреса входящих запросов

### ISSUE THREAD

**Issue by alexbom** [yandex-money/yandex-money-cms-modx#7]
Добрый день.
Мы получили письмо "Новые IP-адреса Яндекс.Кассы".

> Если вы проверяете IP-адреса входящих запросов и ограничиваете доступ на уровне сети, добавьте эти IP в разрешённые...

Предусмотрено ли ограничение по IP вашим сниппетом?
Если да, то куда прописывать новые IP?
Если нет, то подскажите, пожалуйста, как добавить данное ограничение?

На сколько я понимаю, без него присутствует серьёзная дырка в безопасности платежей.

**Comment by ostulov** [comment]
Добрый день!

Данное письмо было направлено магазинам, которые подключены по новому протоколу приема платежей. Для этого протокола подходит другой модуль - https://github.com/yandex-money/yandex-money-cms-v2-shopkeeper
Нет, в нашем модуле не предусмотрены ограничения по IP. 
При необходимости Вы можете установить ограничения самостоятельно через настройки сервера.

Ограничение по IP является дополнительной защитой. Основной защитой является набор уникальных для магазина и для заказа ключей.
